version: "3.6"

services:
  backend:
    build: 
      context: .
      network: host
      dockerfile: dockerfile.backend
    links:
      - mongo
      - redis
    volumes:
      - ./packages/backend:/usr/app/packages/backend:z
      - ./packages/shared/build:/usr/app/packages/shared/build:z
    ports: ["127.0.0.1:7000:7000"]
    command: yarn workspace @truecost/backend start

  frontend:
    build: 
      context: .
      network: host
      dockerfile: dockerfile.frontend
    links:
      - backend
    volumes:
      - ./packages/frontend:/usr/app/packages/frontend:z
      - ./packages/shared/build:/usr/app/packages/shared/build:z
    ports: ["127.0.0.1:8000:8000"]
    command: yarn workspace @truecost/frontend start

  mongo:
    image: library/mongo:bionic
    restart: always
    ports: ["127.0.0.1:27017:27017"]
    volumes: ["mongo:/data/db"]
  redis:
    image: bitnami/redis
    restart: always
    ports: ["127.0.0.1:6379:6379"]
    environment: 
      ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mongo:
