export enum StatusType {
    AWAITING_FOR_PAYMENT = 'AWAITING_FOR_PAYMENT',
    AWAITING_FOR_CONTACT = 'AWAITING_FOR_CONTACT',
    BOOSTER_SEARCH = 'BOOSTER_SEARCH',
    IN_PROGRESS = 'IN_PROGRESS',
    PAUSED = 'PAUSED',
    DONE = 'DONE',
    CLOSED = 'CLOSED'
}