/*eslint-disable*/
const prefix: Record<number, string> = {
    [660]: "UTC-11",
    [600]: "UTC-10 ",
    [570]: "UTC-9:30 ",
    [540]: "UTC-9 ",
    [480]: "UTC-8 ",
    [420]: "UTC-7 ",
    [360]: "UTC-6 ",
    [300]: "UTC-5 ",
    [240]: "UTC-4 ",
    [210]: "UTC-3:30 ",
    [180]: "UTC-3 ",
    [120]: "UTC-2 ",
    [60]: "UTC-1 ",
    [0]: "UTC+0 ",
    [-60]: "UTC+1 ",
    [-120]: "UTC+2 ",
    [-180]: "UTC+3 ",
    [-210]: "UTC+3:30 ",
    [-240]: "UTC+4 ",
    [-270]: "UTC+4:30 ",
    [-300]: "UTC+5 ",
    [-330]: "UTC+5:30 ",
    [-345]: "UTC+5:45 ",
    [-360]: "UTC+6 ",
    [-390]: "UTC+6:30 ",
    [-420]: "UTC+7 ",
    [-480]: "UTC+8 ",
    [-525]: "UTC+8:45 ",
    [-540]: "UTC+9 ",
    [-570]: "UTC+9:30 ",
    [-600]: "UTC+10 ",
    [-630]: "UTC+10:30 ",
    [-660]: "UTC+11 ",
    [-720]: "UTC+12 ",
    [-765]: "UTC+12:45 ",
    [-780]: "UTC+13 ",
    [-840]: "UTC+14 ",
};

const list: [number, string][] = [
    [660, "Pacific/Midway, United States Minor Outlying Islands"],
    [660, "Pacific/Niue, Niue, Alofi"],
    [660, "Pacific/Pago_Pago, American Samoa, Pago Pago, Tāfuna, Ta`ū, Taulaga"],
    [600, "America/Adak, United States"],
    [600, "Pacific/Honolulu, United States, Honolulu, East Honolulu, Pearl City, Hilo, Kailua"],
    [600, "Pacific/Rarotonga, Cook Islands, Avarua"],
    [600, "Pacific/Tahiti, French Polynesia, Faaa, Papeete, Punaauia, Pirae, Mahina"],
    [570, "Pacific/Marquesas, French Polynesia, Taiohae"],
    [540, "America/Anchorage, United States, Anchorage, Fairbanks, Eagle River, Badger, Knik-Fairview"],
    [540, "America/Juneau, United States, Juneau"],
    [540, "America/Metlakatla, United States"],
    [540, "America/Nome, United States"],
    [540, "America/Sitka, United States, Sitka, Ketchikan"],
    [540, "America/Yakutat, United States"],
    [540, "Pacific/Gambier, French Polynesia"],
    [480, "America/Los_Angeles, United States, Los Angeles, San Diego, San Jose, San Francisco, Seattle"],
    [480, "America/Tijuana, Mexico, Tijuana, Mexicali, Ensenada, Rosarito, Tecate"],
    [480, "America/Vancouver, Canada, Vancouver, Surrey, Okanagan, Victoria, Burnaby"],
    [480, "Pacific/Pitcairn, Pitcairn, Adamstown"],
    [420, "America/Boise, United States, Boise, Meridian, Nampa, Idaho Falls, Pocatello"],
    [420, "America/Cambridge_Bay, Canada"],
    [420, "America/Chihuahua, Mexico, Chihuahua, Ciudad Delicias, Cuauhtémoc, Parral, Nuevo Casas Grandes"],
    [420, "America/Creston, Canada"],
    [420, "America/Dawson, Canada"],
    [420, "America/Dawson_Creek, Canada, Fort St. John, Dawson Creek"],
    [420, "America/Denver, United States, Denver, El Paso, Albuquerque, Colorado Springs, Aurora"],
    [420, "America/Edmonton, Canada, Calgary, Edmonton, Fort McMurray, Red Deer, Lethbridge"],
    [420, "America/Fort_Nelson, Canada"],
    [420, "America/Hermosillo, Mexico, Hermosillo, Ciudad Obregón, Nogales, San Luis Río Colorado, Navojoa"],
    [420, "America/Inuvik, Canada"],
    [420, "America/Mazatlan, Mexico, Culiacán, Mazatlán, Tepic, Los Mochis, La Paz"],
    [420, "America/Ojinaga, Mexico, Juárez, Manuel Ojinaga, Ojinaga"],
    [420, "America/Phoenix, United States, Phoenix, Tucson, Mesa, Chandler, Gilbert"],
    [420, "America/Whitehorse, Canada, Whitehorse"],
    [420, "America/Yellowknife, Canada, Yellowknife"],
    [360, "America/Bahia_Banderas, Mexico, Mezcales, San Vicente, Bucerías, Valle de Banderas"],
    [360, "America/Belize, Belize, Belize City, San Ignacio, Orange Walk, Belmopan, Dangriga"],
    [360, "America/Chicago, United States, Chicago, Houston, San Antonio, Dallas, Austin"],
    [360, "America/Costa_Rica, Costa Rica, San José, Limón, San Francisco, Alajuela, Liberia"],
    [360, "America/El_Salvador, El Salvador, San Salvador, Soyapango, Santa Ana, San Miguel, Mejicanos"],
    [360, "America/Guatemala, Guatemala, Guatemala City, Mixco, Villa Nueva, Petapa, San Juan Sacatepéquez"],
    [360, "America/Indiana/Knox, United States"],
    [360, "America/Indiana/Tell_City, United States, Tell City"],
    [360, "America/Managua, Nicaragua, Managua, León, Masaya, Chinandega, Matagalpa"],
    [360, "America/Matamoros, Mexico, Reynosa, Heroica Matamoros, Nuevo Laredo, Piedras Negras, Ciudad Acuña"],
    [360, "America/Menominee, United States, Menominee, Iron Mountain, Kingsford, Ironwood, Iron River"],
    [360, "America/Merida, Mexico, Mérida, Campeche, Ciudad del Carmen, Kanasín, Valladolid"],
    [360, "America/Mexico_City, Mexico, Mexico City, Iztapalapa, Ecatepec de Morelos, Guadalajara, Puebla"],
    [360, "America/Monterrey, Mexico, Monterrey, Saltillo, Guadalupe, Torreón, Victoria de Durango"],
    [360, "America/North_Dakota/Beulah, United States"],
    [360, "America/North_Dakota/Center, United States"],
    [360, "America/North_Dakota/New_Salem, United States, Mandan"],
    [360, "America/Rainy_River, Canada"],
    [360, "America/Rankin_Inlet, Canada"],
    [360, "America/Regina, Canada, Saskatoon, Regina, Prince Albert, Moose Jaw, North Battleford"],
    [360, "America/Resolute, Canada"],
    [360, "America/Swift_Current, Canada, Swift Current"],
    [360, "America/Tegucigalpa, Honduras, Tegucigalpa, San Pedro Sula, Choloma, La Ceiba, El Progreso"],
    [360, "America/Winnipeg, Canada, Winnipeg, Brandon, Kenora, Portage la Prairie, Thompson"],
    [360, "Pacific/Easter, Chile"],
    [360, "Pacific/Galapagos, Ecuador, Puerto Ayora, Puerto Baquerizo Moreno"],
    [300, "America/Atikokan, Canada"],
    [300, "America/Bogota, Colombia, Bogotá, Cali, Medellín, Barranquilla, Cartagena"],
    [300, "America/Cancun, Mexico, Cancún, Chetumal, Playa del Carmen, Cozumel, Felipe Carrillo Puerto"],
    [300, "America/Cayman, Cayman Islands, George Town, West Bay, Bodden Town, East End, North Side"],
    [300, "America/Detroit, United States, Detroit, Grand Rapids, Warren, Sterling Heights, Ann Arbor"],
    [300, "America/Eirunepe, Brazil, Eirunepé, Benjamin Constant, Envira"],
    [300, "America/Grand_Turk, Turks and Caicos Islands, Cockburn Town"],
    [300, "America/Guayaquil, Ecuador, Guayaquil, Quito, Cuenca, Santo Domingo de los Colorados, Machala"],
    [300, "America/Havana, Cuba, Havana, Santiago de Cuba, Camagüey, Holguín, Guantánamo"],
    [300, "America/Indiana/Indianapolis, United States, Indianapolis, Fort Wayne, South Bend, Carmel, Bloomington"],
    [300, "America/Indiana/Marengo, United States"],
    [300, "America/Indiana/Petersburg, United States"],
    [300, "America/Indiana/Vevay, United States"],
    [300, "America/Indiana/Vincennes, United States, Vincennes, Jasper, Washington, Huntingburg"],
    [300, "America/Indiana/Winamac, United States"],
    [300, "America/Iqaluit, Canada, Iqaluit"],
    [300, "America/Jamaica, Jamaica, Kingston, New Kingston, Spanish Town, Portmore, Montego Bay"],
    [300, "America/Kentucky/Louisville, United States, Louisville, Jeffersonville, New Albany, Jeffersontown, Pleasure Ridge Park"],
    [300, "America/Kentucky/Monticello, United States, Monticello"],
    [300, "America/Lima, Peru, Lima, Arequipa, Callao, Trujillo, Chiclayo"],
    [300, "America/Nassau, Bahamas, Nassau, Lucaya, Freeport, West End, Cooper’s Town"],
    [300, "America/New_York, United States, New York City, Brooklyn, Queens, Philadelphia, Manhattan"],
    [300, "America/Nipigon, Canada"],
    [300, "America/Panama, Panama, Panamá, San Miguelito, Juan Díaz, David, Arraiján"],
    [300, "America/Pangnirtung, Canada"],
    [300, "America/Port-au-Prince, Haiti, Port-au-Prince, Carrefour, Delmas 73, Pétionville, Port-de-Paix"],
    [300, "America/Rio_Branco, Brazil, Rio Branco, Cruzeiro do Sul, Sena Madureira, Tarauacá, Feijó"],
    [300, "America/Thunder_Bay, Canada, Thunder Bay"],
    [300, "America/Toronto, Canada, Toronto, Montréal, Ottawa, Mississauga, Québec"],
    [240, "America/Anguilla, Anguilla, The Valley, Blowing Point Village, Sandy Ground Village, West End Village, East End Village"],
    [240, "America/Antigua, Antigua and Barbuda, Saint John’s, Piggotts, Bolands, Codrington, Parham"],
    [240, "America/Aruba, Aruba, Oranjestad, Tanki Leendert, San Nicolas, Santa Cruz, Paradera"],
    [240, "America/Asuncion, Paraguay, Asunción, Ciudad del Este, San Lorenzo, Capiatá, Lambaré"],
    [240, "America/Barbados, Barbados, Bridgetown, Speightstown, Oistins, Bathsheba, Holetown"],
    [240, "America/Blanc-Sablon, Canada, Lévis"],
    [240, "America/Boa_Vista, Brazil, Boa Vista"],
    [240, "America/Campo_Grande, Brazil, Campo Grande, Dourados, Corumbá, Três Lagoas, Ponta Porã"],
    [240, "America/Caracas, Venezuela, Caracas, Maracaibo, Maracay, Valencia, Barquisimeto"],
    [240, "America/Cuiaba, Brazil, Cuiabá, Várzea Grande, Rondonópolis, Sinop, Barra do Garças"],
    [240, "America/Curacao, Curacao, Willemstad, Sint Michiel Liber"],
    [240, "America/Dominica, Dominica, Roseau, Portsmouth, Berekua, Saint Joseph, Wesley"],
    [240, "America/Glace_Bay, Canada, Sydney, Glace Bay, Sydney Mines"],
    [240, "America/Goose_Bay, Canada, Labrador City, Happy Valley-Goose Bay"],
    [240, "America/Grenada, Grenada, Saint George's, Gouyave, Grenville, Victoria, Saint David’s"],
    [240, "America/Guadeloupe, Guadeloupe, Les Abymes, Baie-Mahault, Le Gosier, Petit-Bourg, Sainte-Anne"],
    [240, "America/Guyana, Guyana, Georgetown, Linden, New Amsterdam, Anna Regina, Bartica"],
    [240, "America/Halifax, Canada, Halifax, Dartmouth, Charlottetown, Lower Sackville, Truro"],
    [240, "America/Kralendijk, Bonaire, Saint Eustatius and Saba, Kralendijk, Oranjestad, The Bottom"],
    [240, "America/La_Paz, Bolivia, Santa Cruz de la Sierra, Cochabamba, La Paz, Sucre, Oruro"],
    [240, "America/Lower_Princes, Sint Maarten, Cul de Sac, Lower Prince’s Quarter, Koolbaai, Philipsburg"],
    [240, "America/Manaus, Brazil, Manaus, Itacoatiara, Parintins, Manacapuru, Coari"],
    [240, "America/Marigot, Saint Martin, Marigot"],
    [240, "America/Martinique, Martinique, Fort-de-France, Le Lamentin, Le Robert, Sainte-Marie, Le François"],
    [240, "America/Moncton, Canada, Moncton, Saint John, Fredericton, Dieppe, Miramichi"],
    [240, "America/Montserrat, Montserrat, Brades, Saint Peters, Plymouth"],
    [240, "America/Porto_Velho, Brazil, Porto Velho, Ji Paraná, Vilhena, Ariquemes, Cacoal"],
    [240, "America/Port_of_Spain, Trinidad and Tobago, Chaguanas, Mon Repos, San Fernando, Port of Spain, Rio Claro"],
    [240, "America/Puerto_Rico, Puerto Rico, San Juan, Bayamón, Carolina, Ponce, Caguas"],
    [240, "America/Santiago, Chile, Santiago, Puente Alto, Antofagasta, Viña del Mar, Valparaíso"],
    [240, "America/Santo_Domingo, Dominican Republic, Santo Domingo, Santiago de los Caballeros, Santo Domingo Oeste, Santo Domingo Este, San Pedro de Macorís"],
    [240, "America/St_Barthelemy, Saint Barthelemy, Gustavia"],
    [240, "America/St_Kitts, Saint Kitts and Nevis, Basseterre, Fig Tree, Market Shop, Saint Paul’s, Middle Island"],
    [240, "America/St_Lucia, Saint Lucia, Castries, Bisee, Vieux Fort, Micoud, Soufrière"],
    [240, "America/St_Thomas, U.S. Virgin Islands, Saint Croix, Charlotte Amalie, Cruz Bay"],
    [240, "America/St_Vincent, Saint Vincent and the Grenadines, Kingstown, Kingstown Park, Georgetown, Barrouallie, Port Elizabeth"],
    [240, "America/Thule, Greenland"],
    [240, "America/Tortola, British Virgin Islands, Road Town"],
    [240, "Atlantic/Bermuda, Bermuda, Hamilton"],
    [210, "America/St_Johns, Canada, St. John's, Mount Pearl, Corner Brook, Conception Bay South, Bay Roberts"],
    [180, "America/Araguaina, Brazil, Palmas, Araguaína, Gurupi, Miracema do Tocantins, Porto Franco"],
    [180, "America/Argentina/Buenos_Aires, Argentina, Buenos Aires, La Plata, Mar del Plata, Morón, Bahía Blanca"],
    [180, "America/Argentina/Catamarca, Argentina, San Fernando del Valle de Catamarca, Trelew, Puerto Madryn, Esquel, Rawson"],
    [180, "America/Argentina/Cordoba, Argentina, Córdoba, Rosario, Santa Fe, Resistencia, Santiago del Estero"],
    [180, "America/Argentina/Jujuy, Argentina, San Salvador de Jujuy, San Pedro de Jujuy, Libertador General San Martín, Palpalá, La Quiaca"],
    [180, "America/Argentina/La_Rioja, Argentina, La Rioja, Chilecito, Arauco, Chamical"],
    [180, "America/Argentina/Mendoza, Argentina, Mendoza, San Rafael, San Martín"],
    [180, "America/Argentina/Rio_Gallegos, Argentina, Comodoro Rivadavia, Río Gallegos, Caleta Olivia, Pico Truncado, Puerto Deseado"],
    [180, "America/Argentina/Salta, Argentina, Salta, Neuquén, Santa Rosa, San Carlos de Bariloche, Cipolletti"],
    [180, "America/Argentina/San_Juan, Argentina, San Juan, Chimbas, Santa Lucía, Pocito, Caucete"],
    [180, "America/Argentina/San_Luis, Argentina, San Luis, Villa Mercedes, La Punta, Merlo, Justo Daract"],
    [180, "America/Argentina/Tucuman, Argentina, San Miguel de Tucumán, Yerba Buena, Tafí Viejo, Alderetes, Aguilares"],
    [180, "America/Argentina/Ushuaia, Argentina, Ushuaia, Río Grande"],
    [180, "America/Bahia, Brazil, Salvador, Feira de Santana, Vitória da Conquista, Itabuna, Camaçari"],
    [180, "America/Belem, Brazil, Belém, Ananindeua, Macapá, Parauapebas, Marabá"],
    [180, "America/Cayenne, French Guiana, Cayenne, Matoury, Saint-Laurent-du-Maroni, Kourou, Rémire-Montjoly"],
    [180, "America/Fortaleza, Brazil, Fortaleza, São Luís, Natal, Teresina, João Pessoa"],
    [180, "America/Godthab, Greenland, Nuuk, Sisimiut, Ilulissat, Qaqortoq, Aasiaat"],
    [180, "America/Maceio, Brazil, Maceió, Aracaju, Arapiraca, Nossa Senhora do Socorro, São Cristóvão"],
    [180, "America/Miquelon, Saint Pierre and Miquelon, Saint-Pierre, Miquelon"],
    [180, "America/Montevideo, Uruguay, Montevideo, Salto, Paysandú, Las Piedras, Rivera"],
    [180, "America/Paramaribo, Suriname, Paramaribo, Lelydorp, Brokopondo, Nieuw Nickerie, Moengo"],
    [180, "America/Punta_Arenas, Chile, Punta Arenas, Puerto Natales"],
    [180, "America/Recife, Brazil, Recife, Jaboatão, Jaboatão dos Guararapes, Olinda, Paulista"],
    [180, "America/Santarem, Brazil, Santarém, Altamira, Itaituba, Oriximiná, Alenquer"],
    [180, "America/Sao_Paulo, Brazil, São Paulo, Rio de Janeiro, Belo Horizonte, Brasília, Curitiba"],
    [180, "Antarctica/Palmer, Antarctica"],
    [180, "Antarctica/Rothera, Antarctica, La Legua-San Jacinto"],
    [180, "Atlantic/Stanley, Falkland Islands, Stanley"],
    [120, "America/Noronha, Brazil, Itamaracá"],
    [120, "Atlantic/South_Georgia, South Georgia and the South Sandwich Islands, Grytviken"],
    [60, "America/Scoresbysund, Greenland"],
    [60, "Atlantic/Azores, Portugal, Ponta Delgada, Lagoa, Angra do Heroísmo, Rosto de Cão, Rabo de Peixe"],
    [60, "Atlantic/Cape_Verde, Cabo Verde, Praia, Mindelo, Santa Maria, Cova Figueira, Santa Cruz"],
    [0, "Africa/Abidjan, Ivory Coast, Abidjan, Abobo, Bouaké, Daloa, San-Pédro"],
    [0, "Africa/Accra, Ghana, Accra, Kumasi, Tamale, Takoradi, Atsiaman"],
    [0, "Africa/Bamako, Mali, Bamako, Sikasso, Mopti, Koutiala, Ségou"],
    [0, "Africa/Banjul, Gambia, Serekunda, Brikama, Bakau, Banjul, Farafenni"],
    [0, "Africa/Bissau, Guinea-Bissau, Bissau, Bafatá, Gabú, Bissorã, Bolama"],
    [0, "Africa/Conakry, Guinea, Camayenne, Conakry, Nzérékoré, Kindia, Kankan"],
    [0, "Africa/Dakar, Senegal, Dakar, Pikine, Touba, Thiès, Thiès Nones"],
    [0, "Africa/Freetown, Sierra Leone, Freetown, Bo, Kenema, Koidu, Makeni"],
    [0, "Africa/Lome, Togo, Lomé, Sokodé, Kara, Atakpamé, Kpalimé"],
    [0, "Africa/Monrovia, Liberia, Monrovia, Gbarnga, Kakata, Bensonville, Harper"],
    [0, "Africa/Nouakchott, Mauritania, Nouakchott, Nouadhibou, Néma, Kaédi, Rosso"],
    [0, "Africa/Ouagadougou, Burkina Faso, Ouagadougou, Bobo-Dioulasso, Koudougou, Ouahigouya, Banfora"],
    [0, "Africa/Sao_Tome, Sao Tome and Principe, São Tomé, Santo António"],
    [0, "America/Danmarkshavn, Greenland"],
    [0, "Antarctica/Troll, Antarctica"],
    [0, "Atlantic/Canary, Spain, Las Palmas de Gran Canaria, Santa Cruz de Tenerife, La Laguna, Telde, Arona"],
    [0, "Atlantic/Faroe, Faroe Islands, Tórshavn, Klaksvík, Fuglafjørður, Tvøroyri, Miðvágur"],
    [0, "Atlantic/Madeira, Portugal, Funchal, Câmara de Lobos, São Martinho, Caniço, Machico"],
    [0, "Atlantic/Reykjavik, Iceland, Reykjavík, Kópavogur, Hafnarfjörður, Akureyri, Garðabær"],
    [0, "Atlantic/St_Helena, Saint Helena, Jamestown, Georgetown, Edinburgh of the Seven Seas"],
    [0, "Europe/Guernsey, Guernsey, Saint Peter Port, Torteval, Saint Sampson, St Anne, Saint Saviour"],
    [0, "Europe/Isle_of_Man, Isle of Man, Douglas, Ramsey, Peel, Port Erin, Castletown"],
    [0, "Europe/Jersey, Jersey, Saint Helier, Le Hocq"],
    [0, "Europe/Lisbon, Portugal, Lisbon, Porto, Amadora, Braga, Setúbal"],
    [0, "Europe/London, United Kingdom, London, Birmingham, Liverpool, Nottingham, Sheffield"],
    [-60, "Africa/Algiers, Algeria, Algiers, Boumerdas, Oran, Tébessa, Constantine"],
    [-60, "Africa/Bangui, Central African Republic, Bangui, Bimbo, Mbaïki, Berbérati, Kaga Bandoro"],
    [-60, "Africa/Brazzaville, Republic of the Congo, Brazzaville, Pointe-Noire, Dolisie, Kayes, Owando"],
    [-60, "Africa/Casablanca, Morocco, Casablanca, Rabat, Fès, Sale, Marrakesh"],
    [-60, "Africa/Ceuta, Spain, Ceuta, Melilla"],
    [-60, "Africa/Douala, Cameroon, Douala, Yaoundé, Garoua, Kousséri, Bamenda"],
    [-60, "Africa/El_Aaiun, Western Sahara, Laayoune, Dakhla, Laayoune Plage"],
    [-60, "Africa/Kinshasa, Democratic Republic of the Congo, Kinshasa, Masina, Kikwit, Mbandaka, Matadi"],
    [-60, "Africa/Lagos, Nigeria, Lagos, Kano, Ibadan, Kaduna, Port Harcourt"],
    [-60, "Africa/Libreville, Gabon, Libreville, Port-Gentil, Franceville, Oyem, Moanda"],
    [-60, "Africa/Luanda, Angola, Luanda, N’dalatando, Huambo, Lobito, Benguela"],
    [-60, "Africa/Malabo, Equatorial Guinea, Bata, Malabo, Ebebiyin, Aconibe, Añisoc"],
    [-60, "Africa/Ndjamena, Chad, N'Djamena, Moundou, Sarh, Abéché, Kelo"],
    [-60, "Africa/Niamey, Niger, Niamey, Zinder, Maradi, Agadez, Alaghsas"],
    [-60, "Africa/Porto-Novo, Benin, Cotonou, Abomey-Calavi, Djougou, Porto-Novo, Parakou"],
    [-60, "Africa/Tunis, Tunisia, Tunis, Sfax, Sousse, Kairouan, Bizerte"],
    [-60, "Arctic/Longyearbyen, Svalbard and Jan Mayen, Longyearbyen, Olonkinbyen"],
    [-60, "Europe/Amsterdam, Netherlands, Amsterdam, Rotterdam, The Hague, Utrecht, Eindhoven"],
    [-60, "Europe/Andorra, Andorra, Andorra la Vella, les Escaldes, Encamp, Sant Julià de Lòria, la Massana"],
    [-60, "Europe/Belgrade, Serbia, Belgrade, Pristina, Niš, Novi Sad, Prizren"],
    [-60, "Europe/Berlin, Germany, Berlin, Hamburg, Munich, Köln, Frankfurt am Main"],
    [-60, "Europe/Bratislava, Slovakia, Bratislava, Košice, Prešov, Nitra, Žilina"],
    [-60, "Europe/Brussels, Belgium, Brussels, Antwerpen, Gent, Charleroi, Liège"],
    [-60, "Europe/Budapest, Hungary, Budapest, Debrecen, Miskolc, Szeged, Pécs"],
    [-60, "Europe/Copenhagen, Denmark, Copenhagen, Århus, Odense, Aalborg, Frederiksberg"],
    [-60, "Europe/Dublin, Ireland, Dublin, Cork, Luimneach, Gaillimh, Tallaght"],
    [-60, "Europe/Gibraltar, Gibraltar, Gibraltar"],
    [-60, "Europe/Ljubljana, Slovenia, Ljubljana, Maribor, Celje, Kranj, Velenje"],
    [-60, "Europe/Luxembourg, Luxembourg, Luxembourg, Esch-sur-Alzette, Dudelange, Schifflange, Bettembourg"],
    [-60, "Europe/Madrid, Spain, Madrid, Barcelona, Valencia, Sevilla, Zaragoza"],
    [-60, "Europe/Malta, Malta, Birkirkara, Qormi, Mosta, Żabbar, San Pawl il-Baħar"],
    [-60, "Europe/Monaco, Monaco, Monaco, Monte-Carlo, La Condamine"],
    [-60, "Europe/Oslo, Norway, Oslo, Bergen, Trondheim, Stavanger, Drammen"],
    [-60, "Europe/Paris, France, Paris, Marseille, Lyon, Toulouse, Nice"],
    [-60, "Europe/Podgorica, Montenegro, Podgorica, Nikšić, Herceg Novi, Pljevlja, Budva"],
    [-60, "Europe/Prague, Czechia, Prague, Brno, Ostrava, Pilsen, Olomouc"],
    [-60, "Europe/Rome, Italy, Rome, Milan, Naples, Turin, Palermo"],
    [-60, "Europe/San_Marino, San Marino, Serravalle, Borgo Maggiore, San Marino, Domagnano, Fiorentino"],
    [-60, "Europe/Sarajevo, Bosnia and Herzegovina, Sarajevo, Banja Luka, Zenica, Tuzla, Mostar"],
    [-60, "Europe/Skopje, North Macedonia, Skopje, Bitola, Kumanovo, Prilep, Tetovo"],
    [-60, "Europe/Stockholm, Sweden, Stockholm, Göteborg, Malmö, Uppsala, Sollentuna"],
    [-60, "Europe/Tirane, Albania, Tirana, Durrës, Elbasan, Vlorë, Shkodër"],
    [-60, "Europe/Vaduz, Liechtenstein, Schaan, Vaduz, Triesen, Balzers, Eschen"],
    [-60, "Europe/Vatican, Vatican, Vatican City"],
    [-60, "Europe/Vienna, Austria, Vienna, Graz, Linz, Favoriten, Donaustadt"],
    [-60, "Europe/Warsaw, Poland, Warsaw, Łódź, Kraków, Wrocław, Poznań"],
    [-60, "Europe/Zagreb, Croatia, Zagreb, Split, Rijeka, Osijek, Zadar"],
    [-60, "Europe/Zurich, Switzerland, Zürich, Genève, Basel, Bern, Lausanne"],
    [-120, "Africa/Blantyre, Malawi, Lilongwe, Blantyre, Mzuzu, Zomba, Kasungu"],
    [-120, "Africa/Bujumbura, Burundi, Bujumbura, Muyinga, Gitega, Ruyigi, Ngozi"],
    [-120, "Africa/Cairo, Egypt, Cairo, Alexandria, Giza, Port Said, Suez"],
    [-120, "Africa/Gaborone, Botswana, Gaborone, Francistown, Molepolole, Selebi-Phikwe, Maun"],
    [-120, "Africa/Harare, Zimbabwe, Harare, Bulawayo, Chitungwiza, Mutare, Gweru"],
    [-120, "Africa/Johannesburg, South Africa, Cape Town, Durban, Johannesburg, Soweto, Pretoria"],
    [-120, "Africa/Khartoum, Sudan, Khartoum, Omdurman, Nyala, Port Sudan, Kassala"],
    [-120, "Africa/Kigali, Rwanda, Kigali, Butare, Gitarama, Musanze, Gisenyi"],
    [-120, "Africa/Lubumbashi, Democratic Republic of the Congo, Lubumbashi, Mbuji-Mayi, Kisangani, Kananga, Likasi"],
    [-120, "Africa/Lusaka, Zambia, Lusaka, Kitwe, Ndola, Kabwe, Chingola"],
    [-120, "Africa/Maputo, Mozambique, Maputo, Matola, Beira, Nampula, Chimoio"],
    [-120, "Africa/Maseru, Lesotho, Maseru, Mafeteng, Leribe, Maputsoe, Mohale’s Hoek"],
    [-120, "Africa/Mbabane, Eswatini, Manzini, Mbabane, Big Bend, Malkerns, Nhlangano"],
    [-120, "Africa/Tripoli, Libya, Tripoli, Benghazi, Mişrātah, Tarhuna, Al Khums"],
    [-120, "Africa/Windhoek, Namibia, Windhoek, Rundu, Walvis Bay, Oshakati, Swakopmund"],
    [-120, "Asia/Amman, Jordan, Amman, Zarqa, Irbid, Russeifa, Wādī as Sīr"],
    [-120, "Asia/Beirut, Lebanon, Beirut, Ra’s Bayrūt, Tripoli, Sidon, Tyre"],
    [-120, "Asia/Damascus, Syria, Aleppo, Damascus, Homs, Ḩamāh, Latakia"],
    [-120, "Asia/Famagusta, Cyprus, Famagusta, Kyrenia, Protaras, Paralímni, Rizokárpaso"],
    [-120, "Asia/Gaza, Palestinian Territory, Gaza, Khān Yūnis, Jabālyā, Rafaḩ, Dayr al Balaḩ"],
    [-120, "Asia/Hebron, Palestinian Territory, East Jerusalem, Hebron, Nablus, Battir, Ţūlkarm"],
    [-120, "Asia/Jerusalem, Israel, Jerusalem, Tel Aviv, West Jerusalem, Haifa, Ashdod"],
    [-120, "Asia/Nicosia, Cyprus, Nicosia, Limassol, Larnaca, Stróvolos, Paphos"],
    [-120, "Europe/Athens, Greece, Athens, Thessaloníki, Pátra, Piraeus, Lárisa"],
    [-120, "Europe/Bucharest, Romania, Bucharest, Sector 3, Sector 6, Sector 2, Iaşi"],
    [-120, "Europe/Chisinau, Moldova, Chisinau, Tiraspol, Bălţi, Bender, Rîbniţa"],
    [-120, "Europe/Helsinki, Finland, Helsinki, Espoo, Tampere, Vantaa, Turku"],
    [-120, "Europe/Kaliningrad, Russia, Kaliningrad, Chernyakhovsk, Sovetsk, Baltiysk, Gusev"],
    [-120, "Europe/Kiev, Ukraine, Kyiv, Kharkiv, Dnipro, Donetsk, Odessa"],
    [-120, "Europe/Mariehamn, Aland Islands, Mariehamn"],
    [-120, "Europe/Riga, Latvia, Riga, Daugavpils, Liepāja, Jelgava, Jūrmala"],
    [-120, "Europe/Sofia, Bulgaria, Sofia, Plovdiv, Varna, Burgas, Ruse"],
    [-120, "Europe/Tallinn, Estonia, Tallinn, Tartu, Narva, Kohtla-Järve, Pärnu"],
    [-120, "Europe/Uzhgorod, Ukraine, Uzhgorod, Mukachevo, Khust, Berehove, Tyachiv"],
    [-120, "Europe/Vilnius, Lithuania, Vilnius, Kaunas, Klaipėda, Šiauliai, Panevėžys"],
    [-120, "Europe/Zaporozhye, Ukraine, Zaporizhia, Luhansk, Sevastopol, Melitopol, Syevyerodonets’k"],
    [-180, "Africa/Addis_Ababa, Ethiopia, Addis Ababa, Dire Dawa, Mek'ele, Nazrēt, Bahir Dar"],
    [-180, "Africa/Asmara, Eritrea, Asmara, Keren, Massawa, Assab, Mendefera"],
    [-180, "Africa/Dar_es_Salaam, Tanzania, Dar es Salaam, Mwanza, Zanzibar, Arusha, Mbeya"],
    [-180, "Africa/Djibouti, Djibouti, Djibouti, 'Ali Sabieh, Tadjourah, Obock, Dikhil"],
    [-180, "Africa/Juba, South Sudan, Juba, Winejok, Malakal, Wau, Pajok"],
    [-180, "Africa/Kampala, Uganda, Kampala, Gulu, Lira, Mbarara, Jinja"],
    [-180, "Africa/Mogadishu, Somalia, Mogadishu, Hargeysa, Berbera, Kismayo, Marka"],
    [-180, "Africa/Nairobi, Kenya, Nairobi, Mombasa, Nakuru, Eldoret, Kisumu"],
    [-180, "Antarctica/Syowa, Antarctica"],
    [-180, "Asia/Aden, Yemen, Sanaa, Al Ḩudaydah, Ta‘izz, Aden, Mukalla"],
    [-180, "Asia/Baghdad, Iraq, Baghdad, Basrah, Al Mawşil al Jadīdah, Al Başrah al Qadīmah, Mosul"],
    [-180, "Asia/Bahrain, Bahrain, Manama, Al Muharraq, Ar Rifā‘, Dār Kulayb, Madīnat Ḩamad"],
    [-180, "Asia/Kuwait, Kuwait, Al Aḩmadī, Ḩawallī, As Sālimīyah, Şabāḩ as Sālim, Al Farwānīyah"],
    [-180, "Asia/Qatar, Qatar, Doha, Ar Rayyān, Umm Şalāl Muḩammad, Al Wakrah, Al Khawr"],
    [-180, "Asia/Riyadh, Saudi Arabia, Riyadh, Jeddah, Mecca, Medina, Sulţānah"],
    [-180, "Europe/Istanbul, Turkey, Istanbul, Ankara, İzmir, Bursa, Adana"],
    [-180, "Europe/Kirov, Russia, Kirov, Kirovo-Chepetsk, Vyatskiye Polyany, Slobodskoy, Kotel’nich"],
    [-180, "Europe/Minsk, Belarus, Minsk, Homyel', Mahilyow, Vitebsk, Hrodna"],
    [-180, "Europe/Moscow, Russia, Moscow, Saint Petersburg, Nizhniy Novgorod, Kazan, Rostov-na-Donu"],
    [-180, "Europe/Simferopol, Russia, Simferopol, Kerch, Yevpatoriya, Yalta, Feodosiya"],
    [-180, "Indian/Antananarivo, Madagascar, Antananarivo, Toamasina, Antsirabe, Fianarantsoa, Mahajanga"],
    [-180, "Indian/Comoro, Comoros, Moroni, Moutsamoudou, Fomboni, Domoni, Tsimbeo"],
    [-180, "Indian/Mayotte, Mayotte, Mamoudzou, Koungou, Dzaoudzi, Dembeni, Sada"],
    [-210, "Asia/Tehran, Iran, Tehran, Mashhad, Isfahan, Karaj, Tabriz"],
    [-240, "Asia/Baku, Azerbaijan, Baku, Ganja, Sumqayıt, Lankaran, Yevlakh"],
    [-240, "Asia/Dubai, United Arab Emirates, Dubai, Sharjah, Abu Dhabi, Ajman City, Ras Al Khaimah City"],
    [-240, "Asia/Muscat, Oman, Muscat, Seeb, Şalālah, Bawshar, Sohar"],
    [-240, "Asia/Tbilisi, Georgia, Tbilisi, Kutaisi, Batumi, Sokhumi, Zugdidi"],
    [-240, "Asia/Yerevan, Armenia, Yerevan, Gyumri, Vanadzor, Vagharshapat, Hrazdan"],
    [-240, "Europe/Astrakhan, Russia, Astrakhan, Akhtubinsk, Znamensk, Kharabali, Kamyzyak"],
    [-240, "Europe/Samara, Russia, Samara, Tol’yatti, Izhevsk, Syzran’, Novokuybyshevsk"],
    [-240, "Europe/Saratov, Russia, Saratov, Balakovo, Engel’s, Balashov, Vol’sk"],
    [-240, "Europe/Ulyanovsk, Russia, Ulyanovsk, Dimitrovgrad, Inza, Barysh, Novoul’yanovsk"],
    [-240, "Europe/Volgograd, Russia, Volgograd, Volzhskiy, Kamyshin, Mikhaylovka, Uryupinsk"],
    [-240, "Indian/Mahe, Seychelles, Victoria, Anse Boileau, Bel Ombre, Beau Vallon, Cascade"],
    [-240, "Indian/Mauritius, Mauritius, Port Louis, Beau Bassin-Rose Hill, Vacoas, Curepipe, Quatre Bornes"],
    [-240, "Indian/Reunion, Reunion, Saint-Denis, Saint-Paul, Saint-Pierre, Le Tampon, Saint-André"],
    [-270, "Asia/Kabul, Afghanistan, Kabul, Kandahār, Mazār-e Sharīf, Herāt, Jalālābād"],
    [-300, "Antarctica/Mawson, Antarctica"],
    [-300, "Asia/Aqtau, Kazakhstan, Shevchenko, Zhanaozen, Beyneu, Shetpe, Yeraliyev"],
    [-300, "Asia/Aqtobe, Kazakhstan, Aktobe, Kandyagash, Shalqar, Khromtau, Embi"],
    [-300, "Asia/Ashgabat, Turkmenistan, Ashgabat, Türkmenabat, Daşoguz, Mary, Balkanabat"],
    [-300, "Asia/Atyrau, Kazakhstan, Atyrau, Qulsary, Shalkar, Balykshi, Maqat"],
    [-300, "Asia/Dushanbe, Tajikistan, Dushanbe, Khujand, Kŭlob, Bokhtar, Istaravshan"],
    [-300, "Asia/Karachi, Pakistan, Karachi, Lahore, Faisalabad, Rawalpindi, Multan"],
    [-300, "Asia/Oral, Kazakhstan, Oral, Aqsay, Zhänibek, Tasqala, Zhumysker"],
    [-300, "Asia/Qyzylorda, Kazakhstan, Kyzylorda, Baikonur, Novokazalinsk, Aral, Chiili"],
    [-300, "Asia/Samarkand, Uzbekistan, Samarkand, Bukhara, Nukus, Qarshi, Jizzax"],
    [-300, "Asia/Tashkent, Uzbekistan, Tashkent, Namangan, Andijon, Qo‘qon, Chirchiq"],
    [-300, "Asia/Yekaterinburg, Russia, Yekaterinburg, Chelyabinsk, Ufa, Perm, Orenburg"],
    [-300, "Indian/Kerguelen, French Southern Territories, Port-aux-Français"],
    [-300, "Indian/Maldives, Maldives, Male, Fuvahmulah, Hithadhoo, Kulhudhuffushi, Thinadhoo"],
    [-330, "Asia/Colombo, Sri Lanka, Colombo, Dehiwala-Mount Lavinia, Moratuwa, Jaffna, Negombo"],
    [-330, "Asia/Kolkata, India, Mumbai, Delhi, Bengaluru, Kolkāta, Chennai"],
    [-345, "Asia/Kathmandu, Nepal, Kathmandu, Pokhara, Pātan, Biratnagar, Birgañj"],
    [-360, "Antarctica/Vostok, Antarctica"],
    [-360, "Asia/Almaty, Kazakhstan, Almaty, Karagandy, Shymkent, Taraz, Nur-Sultan"],
    [-360, "Asia/Bishkek, Kyrgyzstan, Bishkek, Osh, Jalal-Abad, Karakol, Tokmok"],
    [-360, "Asia/Dhaka, Bangladesh, Dhaka, Chittagong, Khulna, Rājshāhi, Comilla"],
    [-360, "Asia/Omsk, Russia, Omsk, Tara, Kalachinsk, Znamenskoye, Tavricheskoye"],
    [-360, "Asia/Qostanay, Kazakhstan, Kostanay, Rudnyy, Dzhetygara, Arkalyk, Lisakovsk"],
    [-360, "Asia/Thimphu, Bhutan, Thimphu, Punākha, Tsirang, Phuntsholing, Pemagatshel"],
    [-360, "Asia/Urumqi, China, Zhongshan, Ürümqi, Zhanjiang, Shihezi, Huocheng"],
    [-360, "Indian/Chagos, British Indian Ocean Territory"],
    [-390, "Asia/Yangon, Myanmar, Yangon, Mandalay, Nay Pyi Taw, Mawlamyine, Kyain Seikgyi Township"],
    [-390, "Indian/Cocos, Cocos Islands, West Island"],
    [-420, "Antarctica/Davis, Antarctica"],
    [-420, "Asia/Bangkok, Thailand, Bangkok, Samut Prakan, Mueang Nonthaburi, Udon Thani, Chon Buri"],
    [-420, "Asia/Barnaul, Russia, Barnaul, Biysk, Rubtsovsk, Novoaltaysk, Gorno-Altaysk"],
    [-420, "Asia/Hovd, Mongolia, Khovd, Ölgii, Ulaangom, Uliastay, Altai"],
    [-420, "Asia/Ho_Chi_Minh, Vietnam, Ho Chi Minh City, Hanoi, Da Nang, Haiphong, Biên Hòa"],
    [-420, "Asia/Jakarta, Indonesia, Jakarta, Surabaya, Medan, Bandung, Bekasi"],
    [-420, "Asia/Krasnoyarsk, Russia, Krasnoyarsk, Abakan, Norilsk, Achinsk, Kyzyl"],
    [-420, "Asia/Novokuznetsk, Russia, Novokuznetsk, Kemerovo, Prokop’yevsk, Leninsk-Kuznetsky, Kiselëvsk"],
    [-420, "Asia/Novosibirsk, Russia, Novosibirsk, Berdsk, Iskitim, Akademgorodok, Kuybyshev"],
    [-420, "Asia/Phnom_Penh, Cambodia, Phnom Penh, Takeo, Sihanoukville, Battambang, Siem Reap"],
    [-420, "Asia/Pontianak, Indonesia, Pontianak, Tanjung Pinang, Palangkaraya, Singkawang, Sampit"],
    [-420, "Asia/Tomsk, Russia, Tomsk, Seversk, Strezhevoy, Kolpashevo, Asino"],
    [-420, "Asia/Vientiane, Laos, Vientiane, Pakse, Thakhèk, Savannakhet, Luang Prabang"],
    [-420, "Indian/Christmas, Christmas Island, Flying Fish Cove"],
    [-480, "Antarctica/Casey, Antarctica"],
    [-480, "Asia/Brunei, Brunei, Bandar Seri Begawan, Kuala Belait, Seria, Tutong, Bangar"],
    [-480, "Asia/Choibalsan, Mongolia, Baruun-Urt, Choibalsan"],
    [-480, "Asia/Hong_Kong, Hong Kong, Hong Kong, Kowloon, Tsuen Wan, Yuen Long Kau Hui, Tung Chung"],
    [-480, "Asia/Irkutsk, Russia, Irkutsk, Ulan-Ude, Bratsk, Angarsk, Ust’-Ilimsk"],
    [-480, "Asia/Kuala_Lumpur, Malaysia, Kota Bharu, Kuala Lumpur, Klang, Kampung Baru Subang, Johor Bahru"],
    [-480, "Asia/Kuching, Malaysia, Kuching, Kota Kinabalu, Sandakan, Tawau, Miri"],
    [-480, "Asia/Macau, Macao, Macau"],
    [-480, "Asia/Makassar, Indonesia, Makassar, Denpasar, City of Balikpapan, Banjarmasin, Manado"],
    [-480, "Asia/Manila, Philippines, Quezon City, Manila, Caloocan City, Budta, Davao"],
    [-480, "Asia/Shanghai, China, Shanghai, Beijing, Tianjin, Guangzhou, Shenzhen"],
    [-480, "Asia/Singapore, Singapore, Singapore, Woodlands"],
    [-480, "Asia/Taipei, Taiwan, Taipei, Kaohsiung, Taichung, Tainan, Banqiao"],
    [-480, "Asia/Ulaanbaatar, Mongolia, Ulan Bator, Erdenet, Darhan, Hovd, Murun-kuren"],
    [-480, "Australia/Perth, Australia, Perth, Rockingham, Mandurah, Bunbury, Albany"],
    [-525, "Australia/Eucla, Australia"],
    [-540, "Asia/Chita, Russia, Chita, Krasnokamensk, Borzya, Petrovsk-Zabaykal’skiy, Aginskoye"],
    [-540, "Asia/Dili, Timor Leste, Dili, Maliana, Suai, Likisá, Aileu"],
    [-540, "Asia/Jayapura, Indonesia, Ambon, Jayapura, Sorong, Ternate, Abepura"],
    [-540, "Asia/Khandyga, Russia"],
    [-540, "Asia/Pyongyang, North Korea, Pyongyang, Hamhŭng, Namp’o, Sunch’ŏn, Hŭngnam"],
    [-540, "Asia/Seoul, South Korea, Seoul, Busan, Incheon, Daegu, Daejeon"],
    [-540, "Asia/Tokyo, Japan, Tokyo, Yokohama, Osaka, Nagoya, Sapporo"],
    [-540, "Asia/Yakutsk, Russia, Yakutsk, Blagoveshchensk, Belogorsk, Neryungri, Svobodnyy"],
    [-540, "Pacific/Palau, Palau, Koror, Koror Town, Kloulklubed, Ulimang, Mengellang"],
    [-570, "Australia/Adelaide, Australia, Adelaide, Adelaide Hills, Mount Gambier, Morphett Vale, Gawler"],
    [-570, "Australia/Broken_Hill, Australia, Broken Hill"],
    [-570, "Australia/Darwin, Australia, Darwin, Alice Springs, Palmerston, Howard Springs"],
    [-600, "Antarctica/DumontDUrville, Antarctica"],
    [-600, "Asia/Ust-Nera, Russia"],
    [-600, "Asia/Vladivostok, Russia, Vladivostok, Khabarovsk, Khabarovsk Vtoroy, Komsomolsk-on-Amur, Ussuriysk"],
    [-600, "Australia/Brisbane, Australia, Brisbane, Gold Coast, Logan City, Townsville, Cairns"],
    [-600, "Australia/Currie, Australia"],
    [-600, "Australia/Hobart, Australia, Hobart, Launceston, Burnie, Devonport, Sandy Bay"],
    [-600, "Australia/Lindeman, Australia"],
    [-600, "Australia/Melbourne, Australia, Melbourne, Geelong, Bendigo, Ballarat, Melbourne City Centre"],
    [-600, "Australia/Sydney, Australia, Sydney, Canberra, Newcastle, Wollongong, Maitland"],
    [-600, "Pacific/Chuuk, Micronesia, Weno, Colonia"],
    [-600, "Pacific/Guam, Guam, Dededo Village, Yigo Village, Tamuning, Tamuning-Tumon-Harmon Village, Mangilao Village"],
    [-600, "Pacific/Port_Moresby, Papua New Guinea, Port Moresby, Lae, Mount Hagen, Popondetta, Madang"],
    [-600, "Pacific/Saipan, Northern Mariana Islands, Saipan, San Jose Village"],
    [-630, "Australia/Lord_Howe, Australia"],
    [-660, "Antarctica/Macquarie, Australia"],
    [-660, "Asia/Magadan, Russia, Magadan, Ust-Nera, Susuman, Ola"],
    [-660, "Asia/Sakhalin, Russia, Yuzhno-Sakhalinsk, Korsakov, Kholmsk, Okha, Nevel’sk"],
    [-660, "Asia/Srednekolymsk, Russia"],
    [-660, "Pacific/Bougainville, Papua New Guinea, Arawa, Buka"],
    [-660, "Pacific/Efate, Vanuatu, Port-Vila, Luganville, Isangel, Sola, Lakatoro"],
    [-660, "Pacific/Guadalcanal, Solomon Islands, Honiara, Malango, Auki, Gizo, Buala"],
    [-660, "Pacific/Kosrae, Micronesia, Tofol"],
    [-660, "Pacific/Norfolk, Norfolk Island, Kingston"],
    [-660, "Pacific/Noumea, New Caledonia, Nouméa, Mont-Dore, Dumbéa, Païta, Wé"],
    [-660, "Pacific/Pohnpei, Micronesia, Kolonia, Kolonia Town, Palikir - National Government Center"],
    [-720, "Antarctica/McMurdo, Antarctica"],
    [-720, "Asia/Anadyr, Russia, Anadyr, Bilibino"],
    [-720, "Asia/Kamchatka, Russia, Petropavlovsk-Kamchatsky, Yelizovo, Vilyuchinsk, Klyuchi, Mil’kovo"],
    [-720, "Pacific/Auckland, New Zealand, Auckland, Wellington, Christchurch, Manukau City, North Shore"],
    [-720, "Pacific/Fiji, Fiji, Suva, Lautoka, Nadi, Labasa, Ba"],
    [-720, "Pacific/Funafuti, Tuvalu, Funafuti, Savave Village, Tanrake Village, Toga Village, Asau Village"],
    [-720, "Pacific/Kwajalein, Marshall Islands, Ebaye, Jabat"],
    [-720, "Pacific/Majuro, Marshall Islands, Majuro, Arno, Jabor, Wotje, Mili"],
    [-720, "Pacific/Nauru, Nauru, Yaren, Baiti, Anabar, Uaboe, Ijuw"],
    [-720, "Pacific/Tarawa, Kiribati, Tarawa, Betio Village, Bikenibeu Village"],
    [-720, "Pacific/Wake, United States Minor Outlying Islands"],
    [-720, "Pacific/Wallis, Wallis and Futuna, Mata-Utu, Leava, Alo"],
    [-765, "Pacific/Chatham, New Zealand, Waitangi"],
    [-780, "Pacific/Apia, Samoa, Apia, Asau, Mulifanua, Afega, Leulumoega"],
    [-780, "Pacific/Enderbury, Kiribati"],
    [-780, "Pacific/Fakaofo, Tokelau, Atafu Village, Nukunonu, Fale old settlement"],
    [-780, "Pacific/Tongatapu, Tonga, Nuku‘alofa, Lapaha, Neiafu, Pangai, ‘Ohonua"],
    [-840, "Pacific/Kiritimati, Kiribati"],
];

export const tz = {list, prefix};